# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: keep pure more smile # ex. I m Chuan
name: 纯洁的微笑 # ex. DONGChuan
email: ityouknow@126.com
location: beijing,china # ex. Nice, France
company: cloudfavorites
company_url: https://github.com/cloudfavorites
github_url: https://github.com/ityouknow # ex. https://github.com/DONGChuan
cnblog_url: http://www.cnblogs.com/ityouknow
description: the world is colorful
favicon: favicon.png # Image must be in assets/images
repository: ityouknow/ityouknow.github.io # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://ityouknow.com

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: ityouknow.disqus.com  # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: /
    label: Home

  -
    href: /spring-boot
    label: Spring-Boot
  -
    href: /spring-cloud
    label: Spring-Cloud

#  -
#    href: /open-source
#    label: Open-Source

  -
    href: /blog
    label: Archives

  -
    href: /link
    label: Link
    
  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]
